version: "3.9"
services:
  redis:
    container_name: wefa-redis-cache
    image: redis:4.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
